# DB 연결 정보 (K8S에서 Secret로 주입)
datasource:
  driver-class-name: "org.postgresql.Driver"
  url: "jdbc:postgresql://postgresql:5430"
  username: "local"
  password: "local"

volume-path:
  # for windows
  # for mac
  persistent-volume-data: "/Users/chungchung/my/tools/k8s/volume/local/pv/"
  pod-volume-data: "/Users/chungchung/my/tools/k8s/volume/local/pod/"

# Pod 정보 파일 (Pod의 Volume과 env로 주입)
downward:
  volume:
    filepath: "C:\\volume\\local\\downward-api\\"
  env:
    pod-name: api-tester-3111-94485c47b-5xwsg
    pod-ip: 20.10.10.1
    node-name: test-node

termination:
  message-path: "C:\\volume\\local\\log\\termination.message"

# kube-apiserver 정보 (Secret으로 주입)
api-token:
  url: "https://192.168.56.30.6443"
  filepath: "C:\\volume\\local\\secrets\\"
